WIP: Test implementation
astra137/node-mojang pull request #6
Opened 2017-04-30 16:30 UTC by modev

Since there weren't any test for this package, I just started to add some basic test cases with mocha and chai. I still don't know how to handle the auth tests properly, so I just built a test for the error scenario. Some ideas how to fix this?

2017-04-30 18:01 UTC, jamen commented on test/auth.js
> +  // TODO implement test scenario with valid credentials
For example, before you make the `mojang.auth(...)` calls, setup `nock('https://authserver.mojang.com')` mocks.

2017-04-30 20:03 UTC, modev commented
@jamen  I implemented the HTTP interceptor only for the auth endpoint. I think actually requesting the other resources from the Mojang API helps to recognize breaking changes faster.

2017-04-30 20:05 UTC, jamen commented
:+1:

You don't need to mock all the requests,  just where it makes sense.

2017-05-02 19:55 UTC, modev commented
Tests are done so far. If I'm missing anything please comment. 
But I'm getting a really annoying bug with the _user_ test. It seems to be crashing the username test. I tried to fix this by allowing unmocked requests to bypass the interceptor, but it's still not working. @jamen Any ideas how to fix this?

2017-05-02 20:08 UTC, jamen requested changes

2017-05-02 20:08 UTC, jamen commented on test/history.js
> +  it('with an invalid uuid should reject with error', () => {
You forgot `(done) => ...` here, getting an undefined error.

2017-05-02 20:13 UTC, jamen requested changes

2017-05-02 20:13 UTC, jamen commented on test/user.js
> +describe('mojang.user()', () => {
Maybe you should setup [`after` or `afterEach`](http://stackoverflow.com/questions/16747367/mocha-js-to-run-after-hook-even-if-test-suit-fails) hooks here (and/or inside `username` tests), that does [`nock.cleanAll()`](https://github.com/node-nock/nock#cleanall)

2017-05-02 20:16 UTC, jamen commented
Looks good nice work!  I enabled Travis for you.

2017-05-02 20:30 UTC, jamen approved these changes

2017-05-02 20:31 UTC, jamen commented
:tada:

2017-05-02 20:32 UTC, merged

2017-05-02 20:32 UTC, modev commented
The test hoooks fixed the error. Travis builds the project without any errors. 👍 🎉